development:
  adapter: postgresql
  encoding: unicode
  database: bitpages_development
  pool: 5
  username: AndrewMacAir
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bitpages_production
  pool: 5
  username: AndrewMacAir
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: bitpages_test
  pool: 5
  username: AndrewMacAir
  password:
cucumber:
  <<: *test